<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_LihatLebihBanyak</name>
   <tag></tag>
   <elementGuidId>1ea4986d-655d-42a1-b63a-ffae0df234db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col.text-center > a.btn.btn-outline-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home-portfolio-showcase']/div[4]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce04dc66-af3e-4dce-ac6a-43da79cc8f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary</value>
      <webElementGuid>17f2d942-2745-4fde-abeb-7adfd387b2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.shafiq.id/daftar-investasi</value>
      <webElementGuid>7c8a1081-b022-47e3-bc9b-35d9ef262714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Lebih Banyak</value>
      <webElementGuid>56870c50-fb7e-472a-80fc-8b2fb00d08c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-portfolio-showcase&quot;)/div[@class=&quot;container mt-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col text-center&quot;]/a[@class=&quot;btn btn-outline-primary&quot;]</value>
      <webElementGuid>8048dd63-319f-4179-8b3f-1a1147d63f84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home-portfolio-showcase']/div[4]/div/div/a</value>
      <webElementGuid>62a08c80-6e9f-43a4-babe-dcd45b8b46fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Lebih Banyak')]</value>
      <webElementGuid>8aec85aa-527c-42b7-b933-c780312af4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROI (Proyeksi)'])[8]/following::a[1]</value>
      <webElementGuid>f214c134-c769-4840-80f1-5e424e0ffdf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenor'])[8]/following::a[1]</value>
      <webElementGuid>0ffc608d-4b0e-450a-87ad-71923a150570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengapa Berinvestasi di SHAFIQ'])[1]/preceding::a[1]</value>
      <webElementGuid>b80cfb51-a15b-47d9-b305-2c9bcb042877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anti-GHAIB'])[1]/preceding::a[1]</value>
      <webElementGuid>bb63d24c-245f-4830-a7b9-7ca39ac21284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Lebih Banyak']/parent::*</value>
      <webElementGuid>f6061690-a05e-4817-ab49-23a13d5ea640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.shafiq.id/daftar-investasi')])[18]</value>
      <webElementGuid>c007f597-0fcd-4e06-bd4f-9ea2c72b4986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>c126bc8e-18d1-4c9c-8574-7a5387d7e881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.shafiq.id/daftar-investasi' and (text() = 'Lihat Lebih Banyak' or . = 'Lihat Lebih Banyak')]</value>
      <webElementGuid>ed49c447-5a8b-47b8-91d0-ba6891155b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
