<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Content_Gambar_4</name>
   <tag></tag>
   <elementGuidId>a1b8613a-95cb-4436-b144-a8936b4c9fd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='campaign-gallery']/div/div[5]/img)[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a090a662-3a00-4336-aec9-c762049122f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative z-0 object-cover object-center w-full h-full</value>
      <webElementGuid>ac3d33c4-5109-4129-a825-51a322e82a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.shafiq.id/public/businesses/163/covers/137-abas-03-05-thumb.jpg</value>
      <webElementGuid>6f556f3f-d1ed-418f-9694-a88c69da7bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-portfolio-slider&quot;)/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide portfolio-wrapper&quot;]/div[@class=&quot;portfolio-wrapper&quot;]/div[@class=&quot;overflow-hidden rounded-md card-shadow&quot;]/a[@class=&quot;block relative&quot;]/section[@id=&quot;portfolio-slider&quot;]/div[@id=&quot;campaign-gallery&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide&quot;]/img[@class=&quot;relative z-0 object-cover object-center w-full h-full&quot;]</value>
      <webElementGuid>54951e20-4053-41d2-835e-0f4991251dbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='campaign-gallery']/div/div[5]/img)[4]</value>
      <webElementGuid>0605033f-8a00-4d0c-a030-45fb0fe96511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.shafiq.id/public/businesses/163/covers/137-abas-03-05-thumb.jpg')]</value>
      <webElementGuid>b2b6f451-6f2c-4fc6-83ab-73317c1ee02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a/section/div/div/div[5]/img</value>
      <webElementGuid>f6e1c877-7159-4cab-9e44-ef255022264c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.shafiq.id/public/businesses/163/covers/137-abas-03-05-thumb.jpg']</value>
      <webElementGuid>522af833-fd7e-4de7-8349-0b4faddec4ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
