<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home-slider_ShariaSecuritiesCeowdFunding</name>
   <tag></tag>
   <elementGuidId>232cfd8d-bd78-4895-8208-c7e8cc5a9a89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-slider']/div/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.home-slider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>352b4ac3-8bb6-4259-b8b9-88aa37c2c612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-slider</value>
      <webElementGuid>b7fd2cd7-faad-4ded-9988-20398fe2e5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.shafiq.id/public/sliders/bg_mobile_july.jpeg</value>
      <webElementGuid>ee79815e-fb45-4fbe-ab6a-b7de223349a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-slider&quot;)/div[@class=&quot;swiper-wrapper&quot;]/a[@class=&quot;swiper-slide swiper-slide-active&quot;]/picture[1]/img[@class=&quot;home-slider&quot;]</value>
      <webElementGuid>00672c58-1f39-4fa3-87f5-e4a48516f250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-slider']/div/a/picture/img</value>
      <webElementGuid>5b49272c-a2e4-4d86-9205-c492c142dd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>4eafd8df-9719-4122-96f8-4afced19d92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
