<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_ProfileUser</name>
   <tag></tag>
   <elementGuidId>e40b850e-3e41-4d4d-848f-f0f208f9b17d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='offcanvas']/div[2]/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-full.h-8.w-8.object-center.object-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>df2981d4-6fb2-4958-ade1-0333e818c6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-full h-8 w-8 object-center object-cover</value>
      <webElementGuid>20bc48b4-2c57-4cb0-aa6b-64d80f55a3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.shafiq.id/static/images/50x50.png</value>
      <webElementGuid>4129d0bf-e6cc-47df-8077-0278540643bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header&quot;)/div[@class=&quot;container&quot;]/nav[@class=&quot;[ shafiq-navbar ] navbar navbar-expand-lg&quot;]/div[@id=&quot;offcanvas&quot;]/div[@class=&quot;flex px-4 lg:ml-10 lg:mr-0 mb-8 lg:mb-0 w-full lg:w-auto order-o0 lg:order-o2&quot;]/div[@class=&quot;hidden lg:block dropdown user-dropdown&quot;]/button[@class=&quot;dropdown-toggle bg-transparent focus:outline-none border-0&quot;]/img[@class=&quot;rounded-full h-8 w-8 object-center object-cover&quot;]</value>
      <webElementGuid>d7104e86-68fe-441a-be59-28f66e61262d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='offcanvas']/div[2]/div/button/img</value>
      <webElementGuid>715f9391-7956-4d68-9c13-d2f8fe0e409b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.shafiq.id/static/images/50x50.png')])[2]</value>
      <webElementGuid>a79123ca-d462-4d5e-b26f-aad2e395a2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>e947e8ed-29f2-490e-bc8e-82f6bd1cbe77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.shafiq.id/static/images/50x50.png']</value>
      <webElementGuid>b70f8ffc-4ce7-4f9d-a250-99410ac45f59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
