<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ErrorMessage_TidakBolehKosong_Email</name>
   <tag></tag>
   <elementGuidId>ed80426c-d367-4fbe-adbd-7df547a29d50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='parsley-id-5']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-danger.mt-2.parsley-required</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>246e1199-b3d5-466b-9c81-56db04525d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger mt-2 parsley-required</value>
      <webElementGuid>a77c6ef3-a385-4519-97cb-c7db1448e6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tidak boleh kosong</value>
      <webElementGuid>f83a5da9-7737-47ea-a2f0-bac01e676af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parsley-id-5&quot;)/div[@class=&quot;alert alert-danger mt-2 parsley-required&quot;]</value>
      <webElementGuid>a20c90d2-f66a-4534-8aa5-ff751f18f9e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='parsley-id-5']/div</value>
      <webElementGuid>4017b7a5-c129-4e5c-9069-ed7b948b86ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[5]</value>
      <webElementGuid>8b067b7f-28b9-49fc-b69d-873b648265ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/following::div[9]</value>
      <webElementGuid>66bf638d-e826-4c0e-aee8-487d939399c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/preceding::div[1]</value>
      <webElementGuid>d678c5a7-b3f9-4f89-a1a6-84ac05967774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[3]/preceding::div[11]</value>
      <webElementGuid>1688e0a9-3d6f-416a-b345-49bd8ea2d2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tidak boleh kosong']/parent::*</value>
      <webElementGuid>acbd7565-3888-4fc1-ad37-c18b46f8bb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div</value>
      <webElementGuid>e7726f8b-5752-4e64-bf95-3a813650d149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'tidak boleh kosong' or . = 'tidak boleh kosong')]</value>
      <webElementGuid>c61909ea-e077-433c-adbe-3684df810d0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
