<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home-slider_ShariaSecuritiesCeowdFunding</name>
   <tag></tag>
   <elementGuidId>05781f92-d4cf-4e0f-82a6-2bae870ea4a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-slider']/div/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.home-slider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c0030cae-34ce-4e67-9bc8-6a2d1cf0c899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-slider</value>
      <webElementGuid>f554f016-a4dd-44ff-bdd3-fcc6e2513228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.shafiq.id/public/sliders/bg_mobile_july.jpeg</value>
      <webElementGuid>e25398c4-84a7-4ee1-bb96-65603b18ae13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-slider&quot;)/div[@class=&quot;swiper-wrapper&quot;]/a[@class=&quot;swiper-slide swiper-slide-active&quot;]/picture[1]/img[@class=&quot;home-slider&quot;]</value>
      <webElementGuid>99566e4f-d123-4e7f-b3df-8c20a49f4b6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-slider']/div/a/picture/img</value>
      <webElementGuid>a1a88691-58b7-402c-a1d1-7f232a59b3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>f5836b4c-eef9-49cc-be03-f793ca0bc5d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
