<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pilih Opsi</name>
   <tag></tag>
   <elementGuidId>6fd2be04-1384-472e-a7d9-5bdf227f665e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='choices--source_id-item-choice-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#choices--source_id-item-choice-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0c4ee69-d81b-415c-b933-6611c71266b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choices--source_id-item-choice-1</value>
      <webElementGuid>9a62acdc-9c80-4cb2-8649-a85257f83e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__item dropdown-item py-1 choices__placeholder choices__item--selectable is-highlighted</value>
      <webElementGuid>8798690d-b04f-4489-8edc-0bbcc8e7d9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>66d985f8-bbf1-4c46-a0c9-896b84cae4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>23755c4d-14e5-4cbf-bec1-3454b833aaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select-text</name>
      <type>Main</type>
      <value>Press to select</value>
      <webElementGuid>4e4a71f8-6ac7-4adc-abbb-7b806734a005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>69f7c361-870a-4530-8981-afdd90729e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Opsi</value>
      <webElementGuid>4c41a336-9fcc-4688-b889-496b42bdc5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choices--source_id-item-choice-1&quot;)</value>
      <webElementGuid>53308b56-0c43-4872-82fd-3ec468d1bed3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='choices--source_id-item-choice-1']</value>
      <webElementGuid>a422bceb-4b03-4f63-ab9b-f29dae36a6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form']/div/div/div/div[2]/div/div/div[5]/div/div/div/div[2]/div/div</value>
      <webElementGuid>da808a04-38ee-432c-9780-c43b3807201e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[2]/following::div[3]</value>
      <webElementGuid>443f2c2d-fdc1-4652-92ca-b1dd3f0113cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dari Mana Anda Mengetahui Shafiq?'])[1]/following::div[7]</value>
      <webElementGuid>e762c266-dd19-41bd-beda-c0228df4e430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/preceding::div[1]</value>
      <webElementGuid>fc2b9aca-bfa6-461c-a968-6012bfe1ee5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TikTok'])[1]/preceding::div[2]</value>
      <webElementGuid>8700824b-9d42-4c30-9a37-6a404ada91ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Opsi']/parent::*</value>
      <webElementGuid>c32f2e59-41cb-4e10-bf48-b730098dfc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div</value>
      <webElementGuid>c29c5be6-f759-43a6-ac86-72ba855b3c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'choices--source_id-item-choice-1' and (text() = 'Pilih Opsi' or . = 'Pilih Opsi')]</value>
      <webElementGuid>637ae8ba-f3cf-48e7-b626-9ffc6347198c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
