<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ErrorMessage_PasswordTidakSama</name>
   <tag></tag>
   <elementGuidId>4dc24942-0c15-422c-8352-016401bf0d80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='parsleyEqualto']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#parsleyEqualto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d63e873-2d10-4f90-b712-2731eba0c770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parsleyEqualto</value>
      <webElementGuid>8d44f5a7-9a2f-4566-b1a1-4bc72b61f3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger mt-2</value>
      <webElementGuid>27b3ffd7-67a6-4ab9-90a7-53d18903da3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>password tidak sama</value>
      <webElementGuid>2c5340a0-24ba-49a0-bfd4-f4987426bbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parsleyEqualto&quot;)</value>
      <webElementGuid>d191334d-50a6-4416-bbe6-21fc0242cc08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='parsleyEqualto']</value>
      <webElementGuid>36174ef2-ea92-4921-a0d3-fb1f0a9ac0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form']/div/div/div/div[2]/div/div/div[4]/div[2]</value>
      <webElementGuid>2b12b00d-95d9-4f78-8567-8490efaef89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Kata Sandi'])[1]/following::div[3]</value>
      <webElementGuid>3e0e50a8-06b0-4b6e-bdb9-5553c6ce3612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tidak boleh kosong'])[3]/following::div[4]</value>
      <webElementGuid>80637a69-b818-4359-b7fe-0c594932ecfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dari Mana Anda Mengetahui Shafiq?'])[1]/preceding::div[2]</value>
      <webElementGuid>0b044e2a-7362-4117-a060-84b36ef86a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[2]/preceding::div[2]</value>
      <webElementGuid>b2d37845-018a-4dbb-8be5-b3bd536daff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='password tidak sama']/parent::*</value>
      <webElementGuid>8b5f4102-ff3f-4011-9131-9f56bdd2a4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>b54fd959-b40d-4bed-87d2-caba7e3e5236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'parsleyEqualto' and (text() = 'password tidak sama' or . = 'password tidak sama')]</value>
      <webElementGuid>22afcfc1-9bc9-4fdf-9bc5-a7e17bf7a583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
