<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ErrorMessage_EmailTidakValid</name>
   <tag></tag>
   <elementGuidId>50ad2f59-67e5-46b3-a4e9-8f8fab5db04f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='parsley-id-7']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-danger.mt-2.parsley-type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3bf14828-9403-4331-ba15-d08d6f8171a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger mt-2 parsley-type</value>
      <webElementGuid>7a23719d-2e97-4c1d-b734-0b71bed6dd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>email tidak valid</value>
      <webElementGuid>d243ef2b-25ac-44d4-8a92-73e3499f272e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parsley-id-7&quot;)/div[@class=&quot;alert alert-danger mt-2 parsley-type&quot;]</value>
      <webElementGuid>ad0a8993-b378-4155-8d4d-03e85800fb56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='parsley-id-7']/div</value>
      <webElementGuid>b1f47f17-983c-41ca-8d95-a21a4f283533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[2]</value>
      <webElementGuid>a02980ea-3c4c-4c7d-8e96-2e12294e1b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tidak boleh kosong'])[1]/following::div[3]</value>
      <webElementGuid>c5d6492d-c373-4d31-bbda-9b0aef2fb498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/preceding::div[1]</value>
      <webElementGuid>0ddf5500-6626-439d-8e23-2e4c53715767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Kata Sandi'])[1]/preceding::div[5]</value>
      <webElementGuid>d50023b9-2c5d-4142-a7e0-3d593178857b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='email tidak valid']/parent::*</value>
      <webElementGuid>3e103879-351e-44cc-8ff4-d63058664230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>da523e56-bc6c-4beb-9b7b-6338cbb764cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'email tidak valid' or . = 'email tidak valid')]</value>
      <webElementGuid>e9505fcd-61c9-4f2d-b53d-e636051a1f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
