<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ErrorMessage_TidakBolehKosongLainnya</name>
   <tag></tag>
   <elementGuidId>3f0b7a2e-f2d7-4b51-a1f5-8c5e83ff2847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='parsley-id-15']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-danger.mt-2.parsley-required</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>740f11ec-a2a2-406a-8631-290f05f24190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger mt-2 parsley-required</value>
      <webElementGuid>bfd29242-0e30-4cac-a5c9-798ee641be6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tidak boleh kosong</value>
      <webElementGuid>bdbc1128-5074-4ebd-8ba7-c4b73ee34d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parsley-id-15&quot;)/div[@class=&quot;alert alert-danger mt-2 parsley-required&quot;]</value>
      <webElementGuid>f5bf84d6-d05d-466d-9b5a-1a0d03cd08c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='parsley-id-15']/div</value>
      <webElementGuid>acfc557a-5e48-4992-ba2f-66d32ba62dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lainnya'])[3]/following::div[5]</value>
      <webElementGuid>40e72458-6f29-4c44-aa3d-228285ce0528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::div[6]</value>
      <webElementGuid>d31f38b6-3326-4284-903a-19d7454320aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[2]/preceding::div[5]</value>
      <webElementGuid>097fa119-3c47-41f2-bc9a-ec8dadee852b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[12]</value>
      <webElementGuid>7382f298-56fe-424e-8f0d-45d71721efdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tidak boleh kosong']/parent::*</value>
      <webElementGuid>3b9e5608-b3e6-4742-a5ec-2d540622ad67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div</value>
      <webElementGuid>518fba15-454d-498c-851e-ae07e1f6fa6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'tidak boleh kosong' or . = 'tidak boleh kosong')]</value>
      <webElementGuid>c2c8f0cc-023b-4f9a-bceb-cc2243621c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
